// Manual verify session — long-lived Playwright browser kept open between
// dashboard interactions. QA opens game → backend launches headed Chrome →
// QA verifies each UI element via dashboard commands → registry saved.
//
// One session at a time (singleton). Concurrent sessions would race over the
// shared registry file; restrict to single-QA for MVP.

import path from "node:path";
import { mkdir, readdir, rm } from "node:fs/promises";
import { openBrowser, closeBrowser, type BrowserSession } from "../orchestrator/browser.js";
import { crawl } from "../step1-crawl/crawler.js";
import { discoverUi } from "../step2-detect-ui/resolver.js";
import { resolveExpectedUiElements } from "../registry/expected-ui-elements.js";
import { aiRecoverLocator } from "../step2-detect-ui/ai-recover-locator.js";
import { aiDiscoverState } from "../step2-detect-ui/graph-explorer.js";
import { verifyElement, ELEMENT_VISUAL_CHECK } from "../step2-detect-ui/ai-vision-verify.js";
import { loadAiCatalog } from "../step7-testcase-gen/ai-catalog.js";
import {
  loadCache as loadActionsCache,
  saveCache as saveActionsCache,
  translateCase,
} from "../step7-testcase-gen/case-action-translator.js";
import { executeCase, type CaseResult } from "../step8-run-scenarios/case-executor.js";
import "../step6-build-model/index.js";
import { createParserForGame } from "../step6-build-model/parser-factory.js";
import { parserCache } from "../registry/parser-cache.js";
import { uiRegistry } from "../registry/ui-registry.js";
import { initMeta, meta } from "../registry/meta.js";
import { providerCache } from "../registry/provider-cache.js";
import { gameMechanics, deriveGameMechanics } from "../registry/game-mechanics.js";
import { pragmaticProvider } from "../../adapters/providers/pragmatic.js";
import { dirForGame } from "../registry/paths.js";
import { diffVsBaseline, regionAround } from "../utils/pixel-diff/index.js";
import { dismissPopupsLoop, detectAnyPopup, detectDarkOverlay, isFreeSpinChainActive } from "../utils/ocr-popup.js";
import { resolvePopupKeywords } from "../registry/popup-keywords.js";
import { resolveSubStateHints, SUB_STATE_HINTS_DEFAULTS, interpolateSliderStops, type SubStateHint } from "../registry/sub-state-hints.js";
import { readFile } from "node:fs/promises";
import type { UiRegistry, UiElement } from "../registry/types.js";

export type SessionStatus = {
  active: boolean;
  gameSlug: string | null;
  gameUrl: string | null;
  startedAt: string | null;
  registry: UiRegistry | null;
  verifyState: Record<string, "pending" | "confirmed" | "rejected">;
  subStateSuggestions: SubStateSuggestion[];
  /** P4 — main-state element keys discovery targets (defaults + per-game).
   *  Dashboard diffs this against registry keys to show a "missing" checklist. */
  expectedElements: string[];
  /** P3 — game-specific buttons auto-added to the registry beyond the expected
   *  list. Dashboard highlights these as AI-discovered extras to verify. */
  discoveryAutoAdded: Array<{ key: string; x: number; y: number; confidence: number; note?: string }>;
};

export type SubStateSuggestion = {
  /** Main-state uiKey to click to open this sub-screen. */
  triggerKey: string;
  /** Namespace label to use when storing discovered sub-state elements. */
  stateLabel: string;
  /** Human-readable name shown on dashboard. */
  description: string;
  /** Already discovered (state-label-prefixed entries exist) → don't re-suggest. */
  alreadyDiscovered: boolean;
};

/**
 * Optional friendly labels/descriptions for known main-state buttons. Used
 * only to make suggestions more readable; ALL main-state buttons are
 * suggested for sub-state discovery — clicking spinButton/betPlus/betMinus
 * may also reveal new state (spin-in-progress controls, bet-multiplier
 * popup, etc.). Keys not in this map fall back to autogenerated label.
 */
// Sub-state hints moved to src/pipeline/registry/sub-state-hints.ts (Phase
// 7.1G). Imported as SUB_STATE_HINTS_DEFAULTS — `computeSuggestions` below
// uses defaults; runtime sub-state discovery (manualSession) resolves per
// game via resolveSubStateHints().
const SUB_STATE_HINTS: Record<string, SubStateHint> = SUB_STATE_HINTS_DEFAULTS;

/**
 * Reverse of the SUB_STATE_HINTS stateLabel mapping. Used to migrate
 * legacy registry keys (saved when discover used the stateLabel as namespace
 * prefix, e.g. "autoplay_popup__turboSpinToggle") into the canonical
 * path-style format ("autoButton__turboSpinToggle"). Run once at session
 * start so AI translator + tree display + executor all see consistent keys.
 */
const LEGACY_NAMESPACE_TO_TRIGGER: Record<string, string> = {
  autoplay_popup: "autoButton",
  bet_minus_state: "betMinus",
  bet_plus_state: "betPlus",
  buy_feature_popup: "buyBonusButton",
  menu: "menuButton",
  paytable: "paytableButton",
  history_popup: "historyButton",
  settings: "settingsButton",
  spin_in_progress: "spinButton",
  turbo_state: "turboButton",
};

/**
 * Rename keys with legacy namespace prefixes to canonical trigger-name form.
 * Mutates registry in-place. Returns list of renames performed (for logging).
 * Collisions (canonical key already exists) are skipped — keeps existing.
 */
function migrateLegacyNamespaces(
  registry: UiRegistry,
): Array<{ old: string; new: string; skipped?: boolean }> {
  const renames: Array<{ old: string; new: string; skipped?: boolean }> = [];
  const oldKeys = Object.keys(registry);
  for (const oldKey of oldKeys) {
    const firstDelim = oldKey.indexOf("__");
    if (firstDelim === -1) continue;
    const topNs = oldKey.slice(0, firstDelim);
    const trigger = LEGACY_NAMESPACE_TO_TRIGGER[topNs];
    if (!trigger) continue;
    const newKey = trigger + oldKey.slice(firstDelim);
    if (registry[newKey]) {
      renames.push({ old: oldKey, new: newKey, skipped: true });
      continue;
    }
    (registry as Record<string, UiElement | undefined>)[newKey] = registry[oldKey];
    delete (registry as Record<string, UiElement | undefined>)[oldKey];
    renames.push({ old: oldKey, new: newKey });
  }
  return renames;
}

/**
 * Stricter prompt used for popup/sub-state discovery. Tells AI to ONLY return
 * elements inside the just-opened overlay, ignoring main-game controls in the
 * background. Coord-overlap dedup in discoverSubState is the safety net for
 * cases where AI still includes background buttons.
 */
const POPUP_FOCUS_PROMPT = `A popup, modal, or sub-screen has just opened on top of the main slot-game UI. The popup is typically:
- Centered (or large overlay) on screen
- Has a darker / dimmed background OUTSIDE its bounds
- Contains buttons specific to its function (Buy options, Settings tabs, Paytable info, History rows, etc.)

Identify ONLY the clickable elements INSIDE this popup/overlay. DO NOT include:
- Main-game buttons visible BEHIND or AROUND the popup (e.g. the spin/bet controls in the background)
- Decorative panels or text labels — only actually-clickable buttons/icons/toggles

SLIDERS / PRESET SELECTORS (IMPORTANT):
If the popup contains a slider, a track of numeric preset chips, or a row of selectable values (e.g. an autoplay popup showing "10  20  25  50  75  100"), emit ONE element PER discrete value, using the EXACT visible number in the key:
- Slider name should describe what the slider controls (autospins, betLevel, coinValue, etc.)
- Key pattern: <sliderName>-<value> using kebab-case (e.g. "autospins-10", "autospins-20", "autospins-25", "autospins-50", "autospins-75", "autospins-100")
- Coordinates point at the CENTER of each tick / label / chip — clicking that exact spot must select that value
- Read the label numbers carefully from the screenshot; do NOT invent values that aren't visible
- If the slider only shows a track without numeric labels (continuous slider), instead emit a single handle element with key "<sliderName>-handle"

Other popup buttons (start, stop, close, tabs) should still be emitted as normal semantic keys alongside the slider presets.

If you genuinely cannot identify a popup overlay (e.g. clicking the button just triggered an inline action with no new screen), return an empty elements array.

Return JSON in this shape:
{
  "stateLabel": "<short_kebab_case_label_for_this_popup>",
  "elements": [
    { "key": "kebab-case-key", "x": int, "y": int, "confidence": 0..1, "role": "close|tab|action|toggle|nav|slider-preset|other" }
  ]
}

Rules:
- Use semantic keys describing the popup's role: closeButton, freeSpinsTab, buyMaxButton, prevPageButton, soundToggle, etc.
- For slider presets use role "slider-preset" and the <sliderName>-<value> key pattern described above.
- Coordinates are CSS pixels from top-left of the FULL viewport screenshot.
- confidence 0..1.

JSON only, no prose.`;

function humanizeKey(key: string): string {
  // camelCase → "camel Case"
  return key.replace(/([a-z])([A-Z])/g, "$1 $2");
}

function computeSuggestions(registry: UiRegistry | null): SubStateSuggestion[] {
  if (!registry) return [];
  const keys = Object.keys(registry);
  const out: SubStateSuggestion[] = [];
  for (const triggerKey of keys) {
    if (triggerKey.includes("__")) continue; // skip already-namespaced sub-state keys
    const hint = SUB_STATE_HINTS[triggerKey];
    // State label = triggerKey itself (path-style nesting). Children saved as
    // <triggerKey>__<childKey>. Consistent with per-row [Discover] button.
    const stateLabel = triggerKey;
    const description = hint?.description ?? `State after clicking ${humanizeKey(triggerKey)}`;
    const prefix = `${stateLabel}__`;
    const alreadyDiscovered = keys.some((k) => k.startsWith(prefix));
    out.push({ triggerKey, stateLabel, description, alreadyDiscovered });
  }
  return out;
}

class ManualSessionManager {
  private session: BrowserSession | null = null;
  private gameSlug: string | null = null;
  private gameUrl: string | null = null;
  private startedAt: string | null = null;
  private registry: UiRegistry | null = null;
  private verifyState: Record<string, "pending" | "confirmed" | "rejected"> = {};
  /** P3 — game-specific buttons the AI noticed beyond the expected list during
   *  the last discovery, AUTO-ADDED to the registry as pending. Tracked so the
   *  dashboard can highlight them for QA to verify / rename / remove. */
  private discoveryAutoAdded: Array<{ key: string; x: number; y: number; confidence: number; note?: string }> = [];
  /** P4 — resolved expected-element target keys for the active game (defaults
   *  + per-game overrides). Populated on start/resume; read by status() to feed
   *  the dashboard "missing elements" checklist. */
  private expectedElementKeys: string[] = [];
  /**
   * Wallet balance tracker. Updated from any network response containing
   * `balance=N` (doInit, doSpin, reloadBalance, etc.). Used as priorBalance
   * for case-executor — so first spin's startingBalance isn't null even
   * when the spin response itself doesn't expose startingBalance.
   *
   * Lifecycle: reset on session start/resume/stop. Listener attached once
   * per page; persists across reloads (browser context survives reload).
   */
  private lastBalance: number | null = null;

  /**
   * Game spec extracted from doInit response — used by case-action-translator
   * to generate correct actions (ladder-aware bet adjustment, multi-spin, etc.).
   * Captured automatically from network listener; null until doInit observed.
   */
  private gameSpec: {
    coinValues: number[];     // sc=0.01,0.015,...
    lines: number;            // l=20
    defaultCoin: number;      // defc=0.15
    betLevels: number[];      // bls=20,100,200
    betMin: number;           // total_bet_min=0.2
    betMax: number;           // total_bet_max=10000
    defaultBet: number;       // computed: defc * l
    betLadder: number[];      // computed: coinValues.map(c => c * l)
  } | null = null;

  /**
   * Game mechanic cache loaded from registry on resume(), or derived from
   * first observed balance-changing spin in start(). `undefined` = not yet
   * loaded; `null` = no entry exists; object = available. Avoids repeated
   * disk reads + repeated derivation attempts.
   */
  private gameMechanicsCached: import("../registry/types.js").GameMechanics | null | undefined = undefined;

  async start(url: string, opts: { autoDiscover?: boolean } = {}): Promise<SessionStatus> {
    if (this.session) {
      throw new Error("Session already active — call stop() first");
    }
    // Headed mode so QA can watch what the backend is doing.
    this.session = await openBrowser(false);
    this.gameUrl = url;
    this.startedAt = new Date().toISOString();
    this.lastBalance = null;
    this.attachBalanceTracker();

    const crawled = await crawl(this.session.page, { gameUrl: url });
    this.gameSlug = crawled.gameSlug;
    this.expectedElementKeys = (await resolveExpectedUiElements(this.gameSlug)).map((e) => e.key);
    await initMeta(this.gameSlug, url);
    await providerCache.save(this.gameSlug, {
      provider: crawled.provider,
      gameName: crawled.gameName,
      platform: crawled.platform,
      iframeCount: crawled.iframeCount,
      canvasCount: crawled.canvasCount,
      detectedAt: new Date().toISOString(),
    });

    // OCR popup dismissal — detect "PRESS ANYWHERE TO CONTINUE" etc. and
    // auto-click to clear before UI discovery. Deterministic (Tesseract.js,
    // no AI). Skips if no popup keywords detected.
    try {
      await this.session.page.waitForTimeout(2000); // let popup render
      const r = await dismissPopupsLoop(this.session.page);
      if (r.attempts > 0) console.log(`[manual/ocr] popup dismiss: ok=${r.ok} attempts=${r.attempts} matched=${r.finalDetect.matchedKeywords.join(",")}`);
    } catch (err) {
      console.warn(`[manual/ocr] popup dismiss failed (non-fatal): ${err instanceof Error ? err.message : String(err)}`);
    }

    if (opts.autoDiscover !== false) {
      // Run initial AI discovery so QA has a seed registry to verify.
      // QA can confirm/reject/edit each entry.
      //
      // IMPORTANT: disable AI verify-loop here. In manual mode, the HUMAN is
      // the verifier — AI auto-verify (3 rounds per element) is redundant and
      // adds 30-60s of latency before dashboard becomes interactive. Restore
      // prior env state in finally to avoid leaking globally.
      const prevVerify = process.env.QA_UI_VERIFY_LOOP;
      process.env.QA_UI_VERIFY_LOOP = "0";
      try {
        const { uiMap, autoAdded } = await discoverUi(this.session.page, { slug: this.gameSlug });
        this.registry = uiMap;
        this.discoveryAutoAdded = autoAdded ?? [];
        for (const key of Object.keys(uiMap)) this.verifyState[key] = "pending";
        if (this.discoveryAutoAdded.length > 0) {
          console.log(`[manual] auto-added ${this.discoveryAutoAdded.length} extra button(s): ${this.discoveryAutoAdded.map((a) => a.key).join(", ")}`);
        }
        await uiRegistry.save(this.gameSlug, uiMap);
      } finally {
        if (prevVerify === undefined) delete process.env.QA_UI_VERIFY_LOOP;
        else process.env.QA_UI_VERIFY_LOOP = prevVerify;
      }
    } else {
      // Pure manual mode: empty registry, QA builds it from scratch.
      this.registry = {};
    }

    return this.status();
  }

  status(): SessionStatus {
    return {
      active: this.session !== null,
      gameSlug: this.gameSlug,
      gameUrl: this.gameUrl,
      startedAt: this.startedAt,
      registry: this.registry,
      verifyState: { ...this.verifyState },
      subStateSuggestions: computeSuggestions(this.registry),
      expectedElements: [...this.expectedElementKeys],
      discoveryAutoAdded: [...this.discoveryAutoAdded],
    };
  }

  /** Click at the cached coord of a registered element. QA watches result. */
  async clickElement(uiKey: string): Promise<{ ok: boolean; clickedAt: { x: number; y: number } | null; error?: string }> {
    if (!this.session || !this.registry) return { ok: false, clickedAt: null, error: "no active session" };
    const el = this.registry[uiKey];
    if (!el) return { ok: false, clickedAt: null, error: `uiKey ${uiKey} not in registry` };
    try {
      await this.session.page.mouse.click(el.x, el.y);
      return { ok: true, clickedAt: { x: el.x, y: el.y } };
    } catch (err) {
      return { ok: false, clickedAt: null, error: err instanceof Error ? err.message : String(err) };
    }
  }

  /** Click at arbitrary coord (manual correction). */
  async clickAt(x: number, y: number): Promise<{ ok: boolean; error?: string }> {
    if (!this.session) return { ok: false, error: "no active session" };
    try {
      await this.session.page.mouse.click(x, y);
      return { ok: true };
    } catch (err) {
      return { ok: false, error: err instanceof Error ? err.message : String(err) };
    }
  }

  /** Confirm (verify) an element — marks status verified + verifiedBy QA. */
  async confirm(uiKey: string): Promise<void> {
    if (!this.session || !this.gameSlug || !this.registry) throw new Error("no active session");
    const el = this.registry[uiKey];
    if (!el) throw new Error(`uiKey ${uiKey} not in registry`);
    el.verifiedBy = "QA";
    el.status = "verified";
    el.verifiedAt = new Date().toISOString();
    this.verifyState[uiKey] = "confirmed";
    await uiRegistry.save(this.gameSlug, this.registry);
  }

  /**
   * Bulk verify ALL descendants of a parent element (keys starting with
   * `<parentKey>__`, including grandchildren). The parent itself is NOT
   * touched. Use to verify a whole popup's children in one click (e.g. all
   * autoCountSlide-N slider stops under autoButton).
   */
  async confirmChildren(parentKey: string): Promise<{ ok: boolean; count: number; reason?: string }> {
    if (!this.session || !this.gameSlug || !this.registry) return { ok: false, count: 0, reason: "no active session" };
    const prefix = `${parentKey}__`;
    const childKeys = Object.keys(this.registry).filter((k) => k.startsWith(prefix) && this.registry[k]);
    if (childKeys.length === 0) return { ok: false, count: 0, reason: `no children under ${parentKey}` };
    const now = new Date().toISOString();
    for (const k of childKeys) {
      const el = this.registry[k]!;
      el.verifiedBy = "QA";
      el.status = "verified";
      el.verifiedAt = now;
      this.verifyState[k] = "confirmed";
    }
    await uiRegistry.save(this.gameSlug, this.registry);
    console.log(`[manual] bulk verified ${childKeys.length} children of ${parentKey}`);
    return { ok: true, count: childKeys.length };
  }

  /** QA manually corrects coord by clicking on dashboard screenshot. */
  async updateCoord(uiKey: string, x: number, y: number): Promise<void> {
    if (!this.session || !this.gameSlug || !this.registry) throw new Error("no active session");
    const existing = this.registry[uiKey];
    const now = new Date().toISOString();
    const updated: UiElement = {
      x: Math.round(x),
      y: Math.round(y),
      strategy: "manual",
      confidence: 1.0,
      detectedAt: now,
      baselineScreenshot: existing?.baselineScreenshot,
      verifiedBy: "QA",
      status: "verified",
      verifiedAt: now,
    };
    this.registry[uiKey] = updated;
    this.verifyState[uiKey] = "confirmed";
    await uiRegistry.save(this.gameSlug, this.registry);
  }

  /** Add a brand-new element (not in current registry). Rejects if key exists. */
  async addElement(uiKey: string, x: number, y: number): Promise<void> {
    if (!this.session || !this.gameSlug || !this.registry) throw new Error("no active session");
    if (this.registry[uiKey]) throw new Error(`uiKey '${uiKey}' already exists — use Pick in Game on its row to update, or Remove first`);
    const now = new Date().toISOString();
    const el: UiElement = {
      x: Math.round(x),
      y: Math.round(y),
      strategy: "manual",
      confidence: 1.0,
      detectedAt: now,
      verifiedBy: "QA",
      status: "verified",
      verifiedAt: now,
    };
    this.registry[uiKey] = el;
    this.verifyState[uiKey] = "confirmed";
    await uiRegistry.save(this.gameSlug, this.registry);
  }

  /**
   * Multi-level discovery with ANCESTOR PATH WALK + AUTO-RESET to main state.
   *
   * For nested triggers like "buyBonusButton__freeSpinsOption":
   *   1. Close any open popups (ESC ×2 + outside-click) → ensure main state
   *   2. Walk ancestor chain: click buyBonusButton, wait, click freeSpinsOption, wait
   *   3. AI-discover elements in resulting state → save under <triggerKey>__*
   *
   * Works regardless of starting state because step 1 force-resets to main.
   */
  async discoverVia(triggerKey: string, stateLabel: string): Promise<{ ok: boolean; addedKeys?: string[]; reason?: string; clickedPath?: Array<{ key: string; x: number; y: number }> }> {
    if (!this.session || !this.gameSlug || !this.registry) return { ok: false, reason: "no active session" };

    // 1. Reset to main state. Send ESC twice to close any nested popups, then
    //    click an empty corner to dismiss any non-ESC-respecting overlay. Slot
    //    games typically close popups via either ESC or background-click.
    const vp = this.session.page.viewportSize() ?? { width: 1280, height: 720 };
    try {
      await this.session.page.keyboard.press("Escape");
      await this.session.page.waitForTimeout(300);
      await this.session.page.keyboard.press("Escape");
      await this.session.page.waitForTimeout(300);
      // Click top-left corner (empty area, no game UI normally there) as
      // additional outside-click dismissal. Safe coord.
      await this.session.page.mouse.click(5, 5);
      await this.session.page.waitForTimeout(500);
    } catch {
      // Reset failures non-fatal — proceed with walk anyway.
    }
    void vp;

    // 2. Build ancestor chain: "a__b__c" → ["a", "a__b", "a__b__c"]
    const parts = triggerKey.split("__");
    const ancestors: string[] = [];
    for (let i = 1; i <= parts.length; i++) ancestors.push(parts.slice(0, i).join("__"));

    const clickedPath: Array<{ key: string; x: number; y: number }> = [];
    for (const key of ancestors) {
      const el = this.registry[key];
      if (!el) {
        return { ok: false, reason: `ancestor missing in registry: ${key} (need to discover + verify it first)`, clickedPath };
      }
      try {
        await this.session.page.mouse.click(el.x, el.y);
        clickedPath.push({ key, x: el.x, y: el.y });
      } catch (err) {
        return { ok: false, reason: `click on ${key} (${el.x},${el.y}) failed: ${err instanceof Error ? err.message : String(err)}`, clickedPath };
      }
      // Wait for popup to animate in + settle before next click or discovery.
      await this.session.page.waitForTimeout(1500);
    }

    // 3. AI-discover elements at the final state.
    const discovered = await this.discoverSubState(stateLabel);
    return { ...discovered, clickedPath };
  }

  /**
   * Multi-level discovery — after QA opens a popup/sub-screen (e.g. clicks
   * buyBonusButton → popup appears), QA invokes this with a state label.
   * AI vision detects clickable elements with popup-focus prompt:
   *   - Strict instruction to return ONLY popup/overlay elements
   *   - Filter out any element whose coord overlaps a known main-state entry
   *     (within 30px) — AI sometimes still sees main controls faintly through
   *     dimmed background
   */
  async discoverSubState(stateLabel: string): Promise<{ ok: boolean; addedKeys?: string[]; reason?: string }> {
    if (!this.session || !this.gameSlug || !this.registry) return { ok: false, reason: "no active session" };
    const safeLabel = stateLabel.trim().replace(/[^a-zA-Z0-9_]+/g, "_");
    if (!safeLabel) return { ok: false, reason: "stateLabel required (alphanumeric)" };
    const debugDir = path.join(dirForGame(this.gameSlug), "debug-subdiscover");
    await mkdir(debugDir, { recursive: true });
    try {
      // Per-popup discover hint: pin naming conventions / expected children for
      // known states (e.g. autoplay → autoCountSlide-N). The discover flow uses
      // the TRIGGER KEY as the stateLabel/namespace (e.g. "autoButton"), so the
      // hints map (keyed by trigger key) is looked up directly. Fall back to
      // matching by hint.stateLabel for ad-hoc / legacy labels.
      const hints = await resolveSubStateHints(this.gameSlug);
      const matched = hints[safeLabel] ?? Object.values(hints).find((h) => h.stateLabel === safeLabel);
      const prompt = matched?.discoverHint
        ? `${POPUP_FOCUS_PROMPT}\n\n--- STATE-SPECIFIC GUIDANCE (${safeLabel}) ---\n${matched.discoverHint}`
        : POPUP_FOCUS_PROMPT;
      if (matched?.discoverHint) {
        console.log(`[manual/discover] applied discover-hint for "${safeLabel}" (${matched.discoverHint.length} chars)`);
      }
      const result = await aiDiscoverState(this.session.page, debugDir, Date.now(), prompt);
      if (result.elements.length === 0) {
        return { ok: false, reason: "AI returned 0 elements — popup may not be visible" };
      }

      // No dedup — QA wants every AI-returned element registered, even if
      // the coord overlaps an existing entry (e.g., betMinus and betPlus open
      // the SAME panel → same physical chips under different parent namespaces;
      // both names are legitimate keys the AI translator may reference).
      // Same-key under same parent will overwrite (idempotent re-discover).
      const addedKeys: string[] = [];
      const overwrittenKeys: string[] = [];
      const now = new Date().toISOString();
      for (const e of result.elements) {
        const namespacedKey = `${safeLabel}__${e.key}`;
        const wasPresent = Boolean(this.registry[namespacedKey]);
        const el: UiElement = {
          x: Math.round(e.x),
          y: Math.round(e.y),
          strategy: "ai_vision",
          confidence: e.confidence ?? 0.8,
          detectedAt: now,
          status: "pending",
        };
        this.registry[namespacedKey] = el;
        this.verifyState[namespacedKey] = "pending";
        if (wasPresent) overwrittenKeys.push(namespacedKey);
        else addedKeys.push(namespacedKey);
      }
      if (overwrittenKeys.length > 0) {
        console.log(`[manual/discover] overwrote ${overwrittenKeys.length} existing entries with fresh coords: ${overwrittenKeys.slice(0, 5).join(", ")}`);
      }

      // Continuous-slider stop synthesis: if this state has sliderMarks config
      // and the AI returned both track-end anchors, interpolate the discrete
      // stops EVENLY between them. Coords are ESTIMATED (low confidence) — QA
      // re-picks for precision. Anchors are then removed (the marks replace them).
      const sm = matched?.sliderMarks;
      if (sm) {
        const minEl = this.registry[`${safeLabel}__${sm.minAnchor}`];
        const maxEl = this.registry[`${safeLabel}__${sm.maxAnchor}`];
        if (minEl && maxEl && sm.values.length > 0) {
          const n = sm.values.length;
          const stops = interpolateSliderStops(minEl, maxEl, sm.values);
          for (const stop of stops) {
            const key = `${safeLabel}__${sm.keyPrefix}-${stop.value}`;
            const wasPresent = Boolean(this.registry[key]);
            this.registry[key] = {
              x: stop.x,
              y: stop.y,
              strategy: "ai_vision",
              confidence: 0.4, // estimated — QA must re-pick
              detectedAt: now,
              status: "pending",
            };
            this.verifyState[key] = "pending";
            if (!wasPresent) addedKeys.push(key);
          }
          // Remove the raw anchors — the synthesized marks supersede them.
          delete this.registry[`${safeLabel}__${sm.minAnchor}`];
          delete this.registry[`${safeLabel}__${sm.maxAnchor}`];
          delete this.verifyState[`${safeLabel}__${sm.minAnchor}`];
          delete this.verifyState[`${safeLabel}__${sm.maxAnchor}`];
          console.log(`[manual/discover] synthesized ${n} slider stops ${sm.keyPrefix}-{${sm.values.join(",")}} between anchors (estimated — QA re-pick) for ${safeLabel}`);
        } else {
          console.log(`[manual/discover] sliderMarks configured for ${safeLabel} but anchors not found (min=${!!minEl} max=${!!maxEl}) — skipped synthesis`);
        }
      }
      console.log(`[manual/discover] ${addedKeys.length} new + ${overwrittenKeys.length} overwritten under ${safeLabel}__*`);
      await uiRegistry.save(this.gameSlug, this.registry);
      return { ok: true, addedKeys };
    } catch (err) {
      return { ok: false, reason: err instanceof Error ? err.message : String(err) };
    }
  }

  /**
   * Invoke AI recover to suggest a new coord for a single element. QA reviewer
   * then [Click]s the proposed coord to verify; if right → [Confirm], if wrong
   * → [Manual] correction. Doesn't auto-save — QA decides.
   */
  async aiRecover(uiKey: string): Promise<{ ok: boolean; proposed?: { x: number; y: number; confidence: number }; reason?: string }> {
    if (!this.session || !this.registry) return { ok: false, reason: "no active session" };
    try {
      // Build context hint based on whether key is namespaced (sub-state):
      // - Main key (no "__") → no special context
      // - Namespaced (e.g. buy_feature_popup__closeButton) → tell AI a popup is open
      const isNamespaced = uiKey.includes("__");
      const stateLabel = isNamespaced ? uiKey.split("__")[0] : null;
      const contextHint = isNamespaced
        ? `A "${stateLabel}" popup/sub-screen is currently open on top of the main game. Find the element INSIDE that popup, NOT in the background main controls.`
        : undefined;

      const recovered = await aiRecoverLocator(this.session.page, uiKey, { contextHint });
      if (!recovered) return { ok: false, reason: "AI returned no coord — element may not be visible" };

      // STRICT VERIFY: re-check proposed coord with the verifier (crop +
      // describe-and-confirm AI call). Catches AI mistakes like proposing the
      // info "i" icon while we asked for menu "☰". verifier itself may refine
      // the coord across 2 more rounds before giving up.
      const bareKey = isNamespaced ? uiKey.split("__").slice(1).join("__") : uiKey;
      const hasVisualCheck = bareKey in ELEMENT_VISUAL_CHECK;
      let finalCoord = recovered;
      if (hasVisualCheck) {
        const fullBuf = await this.session.page.screenshot({ type: "png" });
        const debugDir = path.join(dirForGame(this.gameSlug), "debug-ai-recover");
        await mkdir(debugDir, { recursive: true });
        const verification = await verifyElement(
          this.session.page,
          bareKey,
          { x: recovered.x, y: recovered.y, confidence: recovered.confidence },
          fullBuf,
          debugDir,
        );
        if (!verification.verified || !verification.finalCoord) {
          const lastTrace = verification.trace[verification.trace.length - 1];
          const what = lastTrace ? lastTrace.what : "unknown";
          return {
            ok: false,
            reason: `AI proposed (${recovered.x},${recovered.y}) but verifier rejected after ${verification.rounds} rounds — actual content at that coord: "${what}". Try [Manual Coord] or re-take screenshot.`,
          };
        }
        // verifier may have refined to a better coord — use that
        finalCoord = {
          ...recovered,
          x: verification.finalCoord.x,
          y: verification.finalCoord.y,
          confidence: verification.finalCoord.confidence,
        };
      }

      // Sanity check for namespaced (popup) keys: reject coord if it overlaps
      // a known main-state element (AI probably saw through the popup).
      if (isNamespaced) {
        const COORD_OVERLAP_PX = 30;
        for (const [k, el] of Object.entries(this.registry)) {
          if (!el || k.includes("__")) continue;
          if (Math.abs(el.x - finalCoord.x) < COORD_OVERLAP_PX && Math.abs(el.y - finalCoord.y) < COORD_OVERLAP_PX) {
            return { ok: false, reason: `Coord (${finalCoord.x},${finalCoord.y}) overlaps main-state ${k} — popup likely not open. Re-open popup and retry.` };
          }
        }
      }

      // Update coord (status pending). QA verifies via [Click] then [Confirm].
      this.registry[uiKey] = {
        ...this.registry[uiKey],
        x: finalCoord.x,
        y: finalCoord.y,
        strategy: "ai_recover",
        confidence: finalCoord.confidence,
        status: "pending",
        detectedAt: finalCoord.detectedAt,
      };
      this.verifyState[uiKey] = "pending";
      return { ok: true, proposed: { x: finalCoord.x, y: finalCoord.y, confidence: finalCoord.confidence } };
    } catch (err) {
      return { ok: false, reason: err instanceof Error ? err.message : String(err) };
    }
  }

  /** Remove a registry entry (e.g. AI hallucinated, doesn't actually exist). */
  async removeElement(uiKey: string): Promise<void> {
    if (!this.session || !this.gameSlug || !this.registry) throw new Error("no active session");
    delete this.registry[uiKey];
    delete this.verifyState[uiKey];
    await uiRegistry.save(this.gameSlug, this.registry);
  }

  /**
   * Click-thru capture: QA clicks DIRECTLY in the Playwright Chrome window.
   * A capture-phase DOM listener intercepts the click → captures (clientX,
   * clientY) → saves to registry → preventDefault so the game doesn't react.
   *
   * Used when AI Recover keeps failing (e.g. menu icon too small / ambiguous).
   * QA just clicks the real button — no screenshot scaling, no manual coord
   * entry. Coord saved with strategy "manual" + verifiedBy: "QA".
   *
   * The listener registers with { once: true } so it auto-removes after one click.
   */
  async captureNextClick(uiKey: string, opts: { timeoutMs?: number; failIfExists?: boolean } = {}): Promise<{ ok: boolean; coord?: { x: number; y: number }; reason?: string }> {
    const timeoutMs = opts.timeoutMs ?? 30000;
    if (!this.session || !this.gameSlug || !this.registry) return { ok: false, reason: "no active session" };
    if (opts.failIfExists && this.registry[uiKey]) {
      return { ok: false, reason: `uiKey '${uiKey}' already exists — use Pick in Game on its row to update, or Remove first` };
    }
    const page = this.session.page;
    try {
      // Pass as plain JS string — TS function would carry esbuild's __name()
      // helper into the browser context and fail with "__name is not defined".
      const captureScript = `
        new Promise(function(resolve) {
          document.addEventListener('mousedown', function(e) {
            e.preventDefault();
            e.stopPropagation();
            resolve({ x: e.clientX, y: e.clientY });
          }, { capture: true, once: true });
        })
      `;
      const result = (await Promise.race([
        page.evaluate(captureScript),
        new Promise((_, reject) =>
          setTimeout(() => reject(new Error(`timeout after ${timeoutMs}ms — no click captured`)), timeoutMs),
        ),
      ])) as { x: number; y: number };

      const now = new Date().toISOString();
      const existing = this.registry[uiKey];
      this.registry[uiKey] = {
        baselineScreenshot: existing?.baselineScreenshot,
        ...(existing ?? {}),
        x: Math.round(result.x),
        y: Math.round(result.y),
        strategy: "manual",
        confidence: 1.0,
        detectedAt: now,
        verifiedBy: "QA",
        status: "verified",
        verifiedAt: now,
      };
      this.verifyState[uiKey] = "confirmed";
      await uiRegistry.save(this.gameSlug, this.registry);
      return { ok: true, coord: { x: Math.round(result.x), y: Math.round(result.y) } };
    } catch (err) {
      return { ok: false, reason: err instanceof Error ? err.message : String(err) };
    }
  }

  /**
   * Navigate the existing browser to a new URL — used when token changes
   * (gameUrl updated) so registry coords can be re-verified live without
   * destroying the session.
   */
  async navigateTo(newUrl: string): Promise<void> {
    if (!this.session) throw new Error("no active session");
    this.gameUrl = newUrl;
    await this.session.page.goto(newUrl, { waitUntil: "domcontentloaded" });
  }

  /** Take a fresh screenshot of the current browser state. */
  async screenshot(): Promise<Buffer | null> {
    if (!this.session) return null;
    return this.session.page.screenshot({ type: "png" });
  }

  /** Load current ocr-regions.json for the active game. Returns empty object
   *  when none exist yet (UI shows "no regions defined" state). */
  async loadOcrRegions(): Promise<{ ok: boolean; regions?: import("../registry/types.js").OcrRegions; reason?: string }> {
    const slug = this.gameSlug;
    if (!slug) return { ok: false, reason: "no active session" };
    const { ocrRegions } = await import("../registry/ocr-regions.js");
    const cur = await ocrRegions.load(slug);
    return { ok: true, regions: cur ?? {} };
  }

  /** Persist a region patch into ocr-regions.json (merge into existing).
   *  Caller passes one or more of balanceArea/betArea/winArea/freeSpinCounter
   *  as `{x, y, width, height}`. */
  async saveOcrRegion(
    key: "balanceArea" | "betArea" | "winArea" | "freeSpinCounter",
    region: { x: number; y: number; width: number; height: number },
  ): Promise<{ ok: boolean; regions?: import("../registry/types.js").OcrRegions; reason?: string }> {
    const slug = this.gameSlug;
    if (!slug) return { ok: false, reason: "no active session" };
    if (region.width <= 0 || region.height <= 0) return { ok: false, reason: "width and height must be positive" };
    const { ocrRegions } = await import("../registry/ocr-regions.js");
    const cur = (await ocrRegions.load(slug)) ?? {};
    const next = { ...cur, [key]: region };
    await ocrRegions.save(slug, next);
    return { ok: true, regions: next };
  }

  /** Delete one region entry from ocr-regions.json. */
  async removeOcrRegion(
    key: "balanceArea" | "betArea" | "winArea" | "freeSpinCounter",
  ): Promise<{ ok: boolean; regions?: import("../registry/types.js").OcrRegions; reason?: string }> {
    const slug = this.gameSlug;
    if (!slug) return { ok: false, reason: "no active session" };
    const { ocrRegions } = await import("../registry/ocr-regions.js");
    const cur = (await ocrRegions.load(slug)) ?? {};
    if (!(key in cur)) return { ok: true, regions: cur };
    const next: Record<string, unknown> = { ...cur };
    delete next[key];
    await ocrRegions.save(slug, next as import("../registry/types.js").OcrRegions);
    return { ok: true, regions: next as import("../registry/types.js").OcrRegions };
  }

  /** Test-fire OCR on a bbox without persisting — QA draws a rectangle, hits
   *  "Test", sees the OCR text + parsed number before committing the region. */
  async testOcrRegion(
    region: { x: number; y: number; width: number; height: number },
  ): Promise<{ ok: boolean; text?: string; parsedValue?: number | null; durationMs?: number; reason?: string }> {
    if (!this.session) return { ok: false, reason: "no active session" };
    if (region.width <= 0 || region.height <= 0) return { ok: false, reason: "width and height must be positive" };
    const { ocrRegion, parseNumericFromOcr } = await import("../utils/ocr-popup.js");
    try {
      const ocr = await ocrRegion(this.session.page, {
        x: region.x,
        y: region.y,
        w: region.width,
        h: region.height,
      });
      return {
        ok: true,
        text: ocr.text,
        parsedValue: parseNumericFromOcr(ocr.text),
        durationMs: ocr.durationMs,
      };
    } catch (err) {
      return { ok: false, reason: err instanceof Error ? err.message : String(err) };
    }
  }

  /**
   * Pre-flight check used before running each test case in a batch — verify
   * the game is sitting on the main play screen, not stuck in a popup or
   * sub-state from the previous case. Two-layer detection (B + C):
   *   B1) OCR keywords: scan screenshot for "PAYTABLE", "CONGRATULATIONS",
   *       "BUY FEATURE", etc. → popup present.
   *   B2) Dark overlay: sample 4 corners' brightness — semi-transparent
   *       popup dimmer means main is covered.
   *   C)  Behavioral probe (opt-in): click spinButton, listen 3s for a
   *       /gameService response. Response → confirmed on main. No response
   *       within 3s → popup/frozen → not on main.
   *
   * Caller can request recovery via `autoRecover: true` — runs ESC×2 +
   * click corner + 1500ms wait, re-detects up to maxRecoverAttempts (2).
   *
   * @returns onMain: final verdict; details: each layer's result; recovered:
   *          true if was off-main but successfully returned via recovery.
   */
  async ensureMainScreen(opts: {
    probe?: boolean;
    autoRecover?: boolean;
    maxRecoverAttempts?: number;
  } = {}): Promise<{
    ok: boolean;
    onMain: boolean;
    recovered: boolean;
    layers: {
      ocr?: { hasPopup: boolean; matched: string[]; durationMs: number };
      overlay?: { overlayPresent: boolean; cornerBrightness: number[]; durationMs: number };
      probe?: { spinFired: boolean; durationMs: number };
    };
    reason?: string;
    attempts: number;
    /** True when off-main was due to a free-spin chain still playing (can't be
     *  dismissed — must wait for it to finish). Callers should poll/wait. */
    fsActive?: boolean;
  }> {
    if (!this.session) return { ok: false, onMain: false, recovered: false, layers: {}, reason: "no active session", attempts: 0 };
    const page = this.session.page;
    const maxAttempts = (opts.autoRecover === false ? 0 : (opts.maxRecoverAttempts ?? 2)) + 1;
    let fsActive = false;
    const layers: {
      ocr?: { hasPopup: boolean; matched: string[]; durationMs: number };
      overlay?: { overlayPresent: boolean; cornerBrightness: number[]; durationMs: number };
      probe?: { spinFired: boolean; durationMs: number };
    } = {};
    let recovered = false;
    // Resolve per-game popup keywords (defaults if no override)
    const popupKws = await resolvePopupKeywords(this.gameSlug);

    for (let attempt = 1; attempt <= maxAttempts; attempt++) {
      // Layer B1: OCR keyword scan
      const ocr = await detectAnyPopup(page, {
        interstitialKeywords: popupKws.interstitial,
        substateKeywords: popupKws.substate,
      });
      layers.ocr = { hasPopup: ocr.hasPopup, matched: ocr.matchedKeywords, durationMs: ocr.durationMs };
      console.log(`[ensure-main] attempt ${attempt} OCR: hasPopup=${ocr.hasPopup} matched=[${ocr.matchedKeywords.join(",")}] ms=${ocr.durationMs}`);

      // Layer B2: dark overlay sampler — reuse OCR screenshot to avoid a
      // second page.screenshot() call (each forces browser repaint in headed
      // mode → flicker). QA_SKIP_DARK_OVERLAY=1 disables this layer entirely.
      const overlay = process.env.QA_SKIP_DARK_OVERLAY === "1"
        ? { overlayPresent: false, cornerBrightness: [] as number[], durationMs: 0 }
        : await detectDarkOverlay(page, { sharedScreenshot: ocr.screenshot });
      layers.overlay = { overlayPresent: overlay.overlayPresent, cornerBrightness: overlay.cornerBrightness, durationMs: overlay.durationMs };
      console.log(`[ensure-main] attempt ${attempt} overlay: present=${overlay.overlayPresent} corners=[${overlay.cornerBrightness.join(",")}]`);

      const popupSignalB = ocr.hasPopup || overlay.overlayPresent;

      // Distinguish an ACTIVE free-spin chain (FS counter / in-progress text,
      // no "press anywhere" dismiss affordance) from a dismissable popup. An
      // active FS chain CANNOT be dismissed (ESC/click won't stop it) — it must
      // play out. Flag it so we skip recovery + let the caller poll/wait.
      fsActive = isFreeSpinChainActive(ocr.matchedKeywords);

      // Layer C: behavioral probe (only when B says "clean" + opt-in)
      if (!popupSignalB && opts.probe === true) {
        const probe = await this.behavioralProbe();
        layers.probe = probe;
        console.log(`[ensure-main] attempt ${attempt} probe: spinFired=${probe.spinFired} ms=${probe.durationMs}`);
        if (probe.spinFired) {
          return { ok: true, onMain: true, recovered, layers, attempts: attempt };
        }
        // Probe failed → treat as off-main; fall through to recovery.
      } else if (!popupSignalB) {
        // B passed, probe not requested → trust B and proceed
        return { ok: true, onMain: true, recovered, layers, attempts: attempt };
      }

      // OFF MAIN → recover, UNLESS a free-spin chain is playing (don't ESC/click
      // an auto-playing chain — just let the caller wait it out).
      if (attempt < maxAttempts) {
        if (fsActive) {
          console.log(`[ensure-main] attempt ${attempt}: free-spin chain in progress → waiting (no dismiss)`);
        } else {
          recovered = true;
          await this.recoverToMain();
        }
      }
    }

    return {
      ok: false,
      onMain: false,
      recovered,
      layers,
      fsActive,
      reason: fsActive
        ? `free-spin chain still playing: ${layers.ocr?.matched.join(", ")}`
        : layers.ocr?.hasPopup
        ? `popup detected: ${layers.ocr.matched.join(", ")}`
        : layers.overlay?.overlayPresent
        ? `dark overlay covering corners [${layers.overlay.cornerBrightness.join(",")}]`
        : layers.probe && !layers.probe.spinFired
        ? "spinButton click did not fire a spin within 3s"
        : "unknown",
      attempts: maxAttempts,
    };
  }

  /**
   * Inter-case wait: poll ensureMainScreen on a 2s tick until we land on
   * the main play screen OR maxWaitMs elapses. Used instead of an arbitrary
   * fixed delay between cases — exits as soon as game is ready so fast cases
   * don't wait 60s, slow cases (free-spin cascade chain) get however long
   * they need within the cap.
   *
   * Returns total elapsed + final state so dashboard can report.
   */
  async waitForMainScreen(opts: { maxWaitMs?: number; pollMs?: number } = {}): Promise<{
    onMain: boolean;
    elapsedMs: number;
    polls: number;
    recoveredCount: number;
    reason?: string;
  }> {
    const maxWait = Math.max(2000, opts.maxWaitMs ?? 90_000);
    // Increased default from 2s → 5s to reduce screenshot frequency (each
    // poll = ~2 screenshots in headed mode → causes browser flicker).
    const pollMs = Math.max(500, opts.pollMs ?? 5000);
    const start = Date.now();
    let polls = 0;
    let recoveredCount = 0;
    while (Date.now() - start < maxWait) {
      polls++;
      const r = await this.ensureMainScreen({ probe: false, autoRecover: true, maxRecoverAttempts: 1 });
      if (r.recovered) recoveredCount++;
      if (r.onMain) {
        console.log(`[wait-for-main] onMain after ${Date.now() - start}ms (${polls} polls, ${recoveredCount} recoveries)`);
        return { onMain: true, elapsedMs: Date.now() - start, polls, recoveredCount };
      }
      // Wait remaining poll window before next check
      const elapsed = Date.now() - start;
      const remaining = maxWait - elapsed;
      if (remaining > 0) await this.session?.page.waitForTimeout(Math.min(pollMs, remaining));
    }
    return {
      onMain: false,
      elapsedMs: Date.now() - start,
      polls,
      recoveredCount,
      reason: `gave up after ${maxWait}ms — game stuck off-main`,
    };
  }

  /**
   * Recovery moves used when off-main detected:
   *   1. Try OCR auto-dismiss loop (handles "PRESS ANYWHERE TO CONTINUE" etc.)
   *   2. Press ESC × 2 (closes most modal popups)
   *   3. Click viewport corner (5, 5) — outside any centered popup
   *   4. Wait 1500ms for animations to settle
   * Doesn't return success; caller re-runs detection to verify.
   */
  private async recoverToMain(): Promise<void> {
    if (!this.session) return;
    const page = this.session.page;
    try {
      const r = await dismissPopupsLoop(page, { maxAttempts: 2 });
      if (r.attempts > 0) console.log(`[recover-main] ocr-dismiss ok=${r.ok} attempts=${r.attempts}`);
    } catch (err) {
      console.warn(`[recover-main] ocr-dismiss failed: ${err instanceof Error ? err.message : String(err)}`);
    }
    try {
      await page.keyboard.press("Escape");
      await page.waitForTimeout(300);
      await page.keyboard.press("Escape");
      await page.waitForTimeout(300);
      await page.mouse.click(5, 5);
      await page.waitForTimeout(1500);
    } catch (err) {
      console.warn(`[recover-main] esc+corner failed: ${err instanceof Error ? err.message : String(err)}`);
    }
  }

  /**
   * Behavioral probe — click the spinButton at its registered coord, listen
   * 3s for any /gameService response. If a spin response fires → confirmed
   * on the main play screen (game accepted the spin). If not → either we're
   * on a popup that swallowed the click, or the game is frozen.
   *
   * Side effect: consumes one real spin (deducts bet from balance, increments
   * roundId). Caller decides whether the cost is worth the confirmation.
   */
  private async behavioralProbe(): Promise<{ spinFired: boolean; durationMs: number }> {
    const start = Date.now();
    if (!this.session || !this.registry?.spinButton) {
      return { spinFired: false, durationMs: Date.now() - start };
    }
    const page = this.session.page;
    const sb = this.registry.spinButton;
    let fired = false;
    const onResponse = (res: import("playwright").Response) => {
      if (/gameService|doSpin/.test(res.url())) fired = true;
    };
    page.on("response", onResponse);
    try {
      await page.mouse.click(sb.x, sb.y);
      // Poll for up to 3s with 100ms granularity so we exit as soon as a spin
      // is observed (no need to wait the full 3s when game is responsive).
      const deadline = Date.now() + 3000;
      while (Date.now() < deadline && !fired) {
        await page.waitForTimeout(100);
      }
    } finally {
      page.off("response", onResponse);
    }
    return { spinFired: fired, durationMs: Date.now() - start };
  }

  /**
   * Resume a previously-registered game — open browser at saved gameUrl,
   * load existing ui-registry.json (no AI discovery). QA can continue
   * verifying / refining without re-running expensive discovery.
   */
  async resume(gameSlug: string): Promise<SessionStatus> {
    if (this.session) throw new Error("Session already active — call stop() first");
    const m = await meta.load(gameSlug);
    if (!m) throw new Error(`No registry for ${gameSlug}`);
    const reg = await uiRegistry.load(gameSlug);
    if (!reg) throw new Error(`No ui-registry.json for ${gameSlug}`);

    // Rename legacy namespace keys (autoplay_popup__* → autoButton__*) so
    // AI translator + tree + executor all see consistent path-style names.
    const renames = migrateLegacyNamespaces(reg);
    const renamedCount = renames.filter((r) => !r.skipped).length;
    if (renamedCount > 0) {
      console.log(`[manual] migrated ${renamedCount} legacy namespace keys on resume: ${renames.filter((r) => !r.skipped).slice(0, 5).map((r) => `${r.old}→${r.new}`).join(", ")}`);
      await uiRegistry.save(gameSlug, reg);
    }

    this.session = await openBrowser(false);
    this.gameUrl = m.gameUrl;
    this.gameSlug = gameSlug;
    this.startedAt = new Date().toISOString();
    this.registry = reg;
    this.discoveryAutoAdded = [];
    this.expectedElementKeys = (await resolveExpectedUiElements(gameSlug)).map((e) => e.key);
    this.lastBalance = null;
    this.attachBalanceTracker();
    // Restore verify state from persisted status field
    this.verifyState = {};
    for (const [k, el] of Object.entries(reg)) {
      if (!el) continue;
      this.verifyState[k] =
        el.status === "verified" ? "confirmed" :
        el.status === "rejected" ? "rejected" : "pending";
    }

    await crawl(this.session.page, { gameUrl: m.gameUrl, gameSlug });

    // OCR popup dismissal after resume (server-side state may still carry
    // celebration popup from previous session).
    try {
      await this.session.page.waitForTimeout(2000);
      const r = await dismissPopupsLoop(this.session.page);
      if (r.attempts > 0) console.log(`[manual/ocr] popup dismiss on resume: ok=${r.ok} attempts=${r.attempts} matched=${r.finalDetect.matchedKeywords.join(",")}`);
    } catch (err) {
      console.warn(`[manual/ocr] popup dismiss failed (non-fatal): ${err instanceof Error ? err.message : String(err)}`);
    }

    return this.status();
  }

  /**
   * Load test cases + translated actions from disk for current game.
   * Returns one summary per case: id, name, category, severity, action count,
   * assertion count, and the actions themselves (for inspection). Used by
   * dashboard to render the Test Cases panel.
   */
  async listCases(slugOverride?: string): Promise<{ ok: boolean; cases?: Array<{
    id: string;
    name: string;
    category: string;
    severity: string;
    setupSummary: string;
    setupInstructions: string;
    actionCount: number;
    assertionCount: number;
    actions: unknown[];
    assertions: Array<{ id: string; description: string; check_code: string }>;
    skipReason?: string;
  }>; reason?: string }> {
    // Accept explicit slug so dashboard can list cases without active session
    // (read-only file lookups; Preview still requires active session).
    const slug = slugOverride ?? this.gameSlug;
    if (!slug) return { ok: false, reason: "gameSlug required (no active session or override)" };
    const catalog = await loadAiCatalog(slug);
    if (!catalog) return { ok: false, reason: `test-cases.json not found for ${slug} — run Generate Cases first` };
    const actionsCache = await loadActionsCache(slug);
    const out = catalog.cases.map((c) => {
      const translated = actionsCache?.cases[c.id];
      return {
        id: c.id,
        name: c.name,
        category: c.category,
        severity: c.severity,
        setupSummary: (c.setup_instructions ?? "").slice(0, 200),
        setupInstructions: c.setup_instructions ?? "",
        actionCount: translated?.actions.length ?? 0,
        assertionCount: c.custom_assertions?.length ?? 0,
        actions: translated?.actions ?? [],
        assertions: (c.custom_assertions ?? []).map((a) => ({
          id: a.id,
          description: a.description,
          check_code: a.check_code,
        })),
        skipReason: translated?.skipReason,
      };
    });
    return { ok: true, cases: out };
  }

  /**
   * Re-translate a single case: call AI translator with current registry +
   * setup_instructions. Used when initial translation skipped (e.g. missing
   * uiKey at translate time, but QA has since added that element via Discover).
   * Updates test-cases.actions.json on disk and returns new translation.
   */
  async retranslateCase(caseId: string, slugOverride?: string): Promise<{ ok: boolean; actions?: unknown[]; skipReason?: string; reason?: string; aiCalled?: boolean }> {
    const slug = slugOverride ?? this.gameSlug;
    if (!slug) return { ok: false, reason: "gameSlug required (no active session or override)" };
    const catalog = await loadAiCatalog(slug);
    if (!catalog) return { ok: false, reason: "test-cases.json not found" };
    const tc = catalog.cases.find((c) => c.id === caseId);
    if (!tc) return { ok: false, reason: `case ${caseId} not in catalog` };

    // Use current in-memory registry if active session for THIS slug, else load from disk.
    const reg = (this.gameSlug === slug && this.registry) ? this.registry : await uiRegistry.load(slug);
    if (!reg) return { ok: false, reason: "no registry available" };

    const translated = await translateCase({
      caseId: tc.id,
      caseName: tc.name,
      category: tc.category,
      setup: tc.setup_instructions ?? "",
      uiMap: reg,
      gameSpec: this.gameSpec ? {
        betLadder: this.gameSpec.betLadder,
        defaultBet: this.gameSpec.defaultBet,
        betMin: this.gameSpec.betMin,
        betMax: this.gameSpec.betMax,
      } : undefined,
      spinCount: tc.spin_count,
      customAssertions: tc.custom_assertions,
    });

    // Persist updated cache — strip aiCalled (in-call signal, not part of cache schema)
    const { aiCalled, ...persistable } = translated;
    const cache = (await loadActionsCache(slug)) ?? {
      schemaVersion: 1 as const,
      generatedAt: new Date().toISOString(),
      cases: {},
    };
    cache.cases[caseId] = persistable;
    cache.generatedAt = new Date().toISOString();
    await saveActionsCache(slug, cache);

    return { ok: true, actions: translated.actions, skipReason: translated.skipReason, aiCalled };
  }

  /**
   * Return the cached translated actions for a case so the dashboard editor
   * can render them. Returns null actions when the case isn't in the cache
   * yet (translation never ran or was reset). Caller decides UX.
   */
  async getCaseActions(caseId: string, slugOverride?: string): Promise<{
    ok: boolean;
    caseId: string;
    actions: import("../step7-testcase-gen/case-action-translator.js").CaseAction[] | null;
    skipReason?: string;
    /** All uiKeys currently in the game's registry (so editor can validate
     *  click.uiKey + offer autocomplete). */
    availableUiKeys: string[];
    reason?: string;
  }> {
    const slug = slugOverride ?? this.gameSlug;
    if (!slug) return { ok: false, caseId, actions: null, availableUiKeys: [], reason: "no active session or override" };
    const cache = await loadActionsCache(slug);
    const reg = (this.gameSlug === slug && this.registry) ? this.registry : await uiRegistry.load(slug);
    const availableUiKeys = reg ? Object.keys(reg) : [];
    if (!cache || !cache.cases[caseId]) {
      return { ok: true, caseId, actions: null, availableUiKeys, reason: "case not in actions cache (run translate first)" };
    }
    const entry = cache.cases[caseId];
    return {
      ok: true,
      caseId,
      actions: entry.actions,
      skipReason: entry.skipReason,
      availableUiKeys,
    };
  }

  /**
   * Persist QA-edited actions for a case. Validates that each click action's
   * uiKey exists in the current registry; rejects the save if any is missing
   * (so we don't corrupt the cache with broken references). Bypasses AI —
   * QA's edit is final.
   */
  async saveCaseActions(
    caseId: string,
    actions: import("../step7-testcase-gen/case-action-translator.js").CaseAction[],
    slugOverride?: string,
  ): Promise<{ ok: boolean; reason?: string; invalidUiKeys?: string[] }> {
    const slug = slugOverride ?? this.gameSlug;
    if (!slug) return { ok: false, reason: "gameSlug required" };
    const reg = (this.gameSlug === slug && this.registry) ? this.registry : await uiRegistry.load(slug);
    if (!reg) return { ok: false, reason: "no registry available — can't validate uiKeys" };

    // Validate shape + uiKey references.
    if (!Array.isArray(actions)) return { ok: false, reason: "actions must be an array" };
    const invalidUiKeys: string[] = [];
    for (const a of actions) {
      if (!a || typeof a !== "object" || typeof (a as { kind: unknown }).kind !== "string") {
        return { ok: false, reason: "each action must be an object with a 'kind' field" };
      }
      if ((a as { kind: string }).kind === "click") {
        const uiKey = (a as { uiKey?: unknown }).uiKey;
        if (typeof uiKey !== "string" || uiKey.length === 0) {
          return { ok: false, reason: "click action requires a non-empty uiKey" };
        }
        if (!reg[uiKey]) invalidUiKeys.push(uiKey);
      }
      if ((a as { kind: string }).kind === "wait_ms") {
        const ms = (a as { ms?: unknown }).ms;
        if (typeof ms !== "number" || !Number.isFinite(ms) || ms < 0) {
          return { ok: false, reason: "wait_ms requires a non-negative number 'ms'" };
        }
      }
    }
    if (invalidUiKeys.length > 0) {
      return {
        ok: false,
        reason: `uiKey(s) missing from registry: ${invalidUiKeys.join(", ")}`,
        invalidUiKeys,
      };
    }

    // Load + update cache. Bypass AI; this is a human edit.
    const cache = (await loadActionsCache(slug)) ?? {
      schemaVersion: 1 as const,
      generatedAt: new Date().toISOString(),
      cases: {},
    };
    cache.cases[caseId] = { caseId, actions };
    cache.generatedAt = new Date().toISOString();
    await saveActionsCache(slug, cache);
    console.log(`[manual/save-actions] ${caseId}: ${actions.length} action(s) saved by QA edit`);
    return { ok: true };
  }

  /**
   * Batch re-translate all cases that are currently skipped (empty actions or
   * have skipReason). Useful after QA has discovered + verified more UI
   * elements — many cases that referenced previously-missing uiKeys can now
   * succeed. Cost = ~$0.02 × N skipped cases.
   */
  async retranslateAllSkipped(opts: { mode?: "skipped" | "all"; slugOverride?: string } = {}): Promise<{ ok: boolean; total?: number; succeeded?: number; stillSkipped?: number; reason?: string }> {
    const mode = opts.mode ?? "skipped";
    const slug = opts.slugOverride ?? this.gameSlug;
    if (!slug) return { ok: false, reason: "gameSlug required" };
    const catalog = await loadAiCatalog(slug);
    if (!catalog) return { ok: false, reason: "test-cases.json not found" };
    const reg = (this.gameSlug === slug && this.registry) ? this.registry : await uiRegistry.load(slug);
    if (!reg) return { ok: false, reason: "no registry available" };

    const cache = (await loadActionsCache(slug)) ?? {
      schemaVersion: 1 as const,
      generatedAt: new Date().toISOString(),
      cases: {},
    };

    // mode=skipped → only cases with no actions or with skipReason
    // mode=all → ALL cases (force re-translate even runnable ones)
    const candidates = mode === "all"
      ? catalog.cases
      : catalog.cases.filter((c) => {
          const t = cache.cases[c.id];
          return !t || t.actions.length === 0 || t.skipReason;
        });

    let succeeded = 0;
    let stillSkipped = 0;
    console.log(`[manual/retranslate-all] ${candidates.length} candidates`);
    for (const c of candidates) {
      const translated = await translateCase({
        caseId: c.id,
        caseName: c.name,
        category: c.category,
        setup: c.setup_instructions ?? "",
        uiMap: reg,
        gameSpec: this.gameSpec ? {
          betLadder: this.gameSpec.betLadder,
          defaultBet: this.gameSpec.defaultBet,
          betMin: this.gameSpec.betMin,
          betMax: this.gameSpec.betMax,
        } : undefined,
        spinCount: c.spin_count,
        customAssertions: c.custom_assertions,
      });
      const { aiCalled: _ac, ...persistable } = translated;
      cache.cases[c.id] = persistable;
      if (translated.skipReason || translated.actions.length === 0) {
        stillSkipped++;
        console.log(`[manual/retranslate-all] ${c.id} still skipped: ${translated.skipReason ?? "no actions"}`);
      } else {
        succeeded++;
        console.log(`[manual/retranslate-all] ${c.id}${translated.aiCalled ? "" : " (no AI, empty setup)"} → ${translated.actions.length} actions`);
      }
    }
    cache.generatedAt = new Date().toISOString();
    await saveActionsCache(slug, cache);
    return { ok: true, total: candidates.length, succeeded, stillSkipped };
  }

  /**
   * Preview a single test case: execute its translated actions against the
   * Playwright browser (clicks at verified registry coords). User watches
   * Chrome window to confirm steps work, dashboard receives per-action trace.
   */
  async previewCase(
    caseId: string,
    opts: { ensureMain?: boolean } = {},
  ): Promise<{ ok: boolean; result?: CaseResult; reason?: string }> {
    if (!this.session || !this.gameSlug || !this.registry) return { ok: false, reason: "no active session" };
    const catalog = await loadAiCatalog(this.gameSlug);
    if (!catalog) return { ok: false, reason: "test-cases.json not found" };
    const tc = catalog.cases.find((c) => c.id === caseId);
    if (!tc) return { ok: false, reason: `case ${caseId} not in catalog` };
    const actionsCache = await loadActionsCache(this.gameSlug);
    const translated = actionsCache?.cases[caseId];
    if (!translated) return { ok: false, reason: "no translated actions for this case — run qa:cold to translate first" };

    // Pre-flight: every case must start on the MAIN game screen. Uses a
    // POLLING wait (not a one-shot check) so a leftover free-spin chain from a
    // PREVIOUS case (shared session state) is WAITED OUT — ensureMainScreen
    // flags FS-active + skips dismiss, and we poll until the chain finishes.
    // Dismissable popups (celebration / buy / paytable) are auto-recovered each
    // poll. Skip entirely when the caller already ensured main (dashboard
    // run-all loop does its own inter-case wait) via { ensureMain: false }.
    const PREFLIGHT_MAX_WAIT_MS = Number(process.env.QA_CASE_PREFLIGHT_MAX_WAIT_MS ?? 90_000);
    if (opts.ensureMain !== false) {
      const w = await this.waitForMainScreen({ maxWaitMs: PREFLIGHT_MAX_WAIT_MS });
      if (!w.onMain) {
        const reason = `not on main before case after ${(w.elapsedMs / 1000).toFixed(0)}s — ${w.reason ?? "could not reach main"}`;
        console.warn(`[preview-case] ${caseId} SKIP — ${reason}`);
        return {
          ok: true,
          result: {
            caseId: tc.id,
            name: tc.name,
            category: tc.category,
            severity: tc.severity,
            status: "skip",
            skipReason: reason,
            actionsExecuted: 0,
            assertions: [],
            spin: null,
            durationMs: 0,
          },
        };
      }
      if (w.recoveredCount > 0) console.log(`[preview-case] ${caseId} reached main before run (${w.polls} polls, ${w.recoveredCount} recoveries, ${(w.elapsedMs / 1000).toFixed(0)}s)`);
    }

    // Factory auto-loads parser kind + bet multiplier from registry. No more
    // ad-hoc setBetMultiplier injection — Phase 7.1B consolidation.
    const parser = await createParserForGame(this.gameSlug);

    // Auto-inject default allowed_interruptions for multi-spin cases (Part B
    // of state-machine runner overhaul). Slot games can randomly trigger
    // free spins / big wins / bonuses on ANY spin — treating that as a
    // failure-by-default is wrong. Any case that fires ≥2 spins should
    // tolerate these expected variations unless the catalog explicitly opts
    // out by setting `allowed_interruptions: []`.
    const spinActionCount = translated.actions.filter((a) => a.kind === "spin").length;
    const DEFAULT_INTERRUPTIONS = ["FREE_SPIN_TRIGGERED", "BIG_WIN_POPUP", "BONUS_POPUP"];
    let resolvedInterruptions = tc.allowed_interruptions;
    if (resolvedInterruptions === undefined && spinActionCount >= 2) {
      resolvedInterruptions = DEFAULT_INTERRUPTIONS;
      console.log(`[case-runner] auto-injected allowed_interruptions=${JSON.stringify(DEFAULT_INTERRUPTIONS)} for multi-spin case "${tc.id}" (${spinActionCount} spins)`);
    }

    const caseInput = {
      id: tc.id,
      name: tc.name,
      category: tc.category,
      severity: tc.severity,
      custom_assertions: tc.custom_assertions,
      minimum_evidence: tc.minimum_evidence,
      allowed_interruptions: resolvedInterruptions,
      on_feature_triggered: tc.on_feature_triggered,
      retry_policy: tc.retry_policy,
      actions: translated.actions,
      skipReason: translated.skipReason,
    };
    const ctx = {
      page: this.session.page,
      uiMap: this.registry,
      parser,
      priorBalance: this.lastBalance,
      // Live read so a multi-attempt retry loop sees the current balance, not
      // the snapshot taken when previewCase was first entered. The executor
      // uses this to seed balanceBefore for the first spin of each attempt.
      liveBalance: () => this.lastBalance,
      gameSlug: this.gameSlug,
    };

    // Retry loop. If the catalog declares a retry_policy, honor it. Otherwise
    // apply the DEFAULT "re-run on fail" behavior: a case that FAILS is re-run
    // exactly ONCE (maxRetries=1); only a persistent fail is recorded. A re-run
    // that passes is recorded as pass. ONLY a hard fail (status === "fail")
    // triggers a retry — INCONCLUSIVE / FAIL_LOW / FLAKY do NOT (retryWhen: []).
    const { runWithRetry } = await import("../step8-run-scenarios/case-retry-loop.js");
    const policy = tc.retry_policy ?? {
      maxRetries: Math.max(0, Math.min(5, Number(process.env.QA_CASE_FAIL_RETRIES ?? 1))),
      retryWhen: [],
      retryOnFailStatus: true,
    };
    // Re-ensure main between attempts (a failed run may have left a popup /
    // mid-feature state). The first attempt relies on the pre-flight above.
    let firstRun = true;
    const executeOnce = async (): Promise<CaseResult> => {
      if (!firstRun && opts.ensureMain !== false) {
        // A failed attempt may have left a popup OR triggered a free-spin chain
        // — poll-wait for main (FS-aware) before re-running.
        const w = await this.waitForMainScreen({ maxWaitMs: PREFLIGHT_MAX_WAIT_MS });
        if (!w.onMain) console.warn(`[preview-case] ${caseId} retry: still off-main after wait — running anyway`);
      }
      firstRun = false;
      return executeCase(ctx, caseInput);
    };
    const loop = await runWithRetry(executeOnce, policy);
    const result = loop.finalResult;
    if (loop.attempts > 1) {
      const history = loop.attemptHistory.map((a) => `#${a.attempt}=${a.outcome ?? a.status}`).join(", ");
      const recovered = result.status === "pass" && loop.attemptHistory[0]?.status === "fail";
      console.log(`[preview-case] ${caseId} ran ${loop.attempts} attempts: ${history}${recovered ? " → recovered (pass after retry)" : ""}`);
      result.warnings = [
        ...(result.warnings ?? []),
        `re-run ${loop.attempts - 1}× (first failed): ${history}`,
      ];
    }
    return { ok: true, result };
  }

  /**
   * Ship C — auto-mode preview. Run case → if outcome ∈ {FAIL_LOW,
   * INCONCLUSIVE} → heuristic-first AI Review. If heuristic ≥ 0.85 +
   * patch exists → auto-apply + rerun once. Skips AI fallback (avoids
   * cost) — if heuristic can't decide, just return the original result.
   *
   * Cap: 1 review + 1 patch + 1 rerun. NO further AI fallback or loop.
   * Loop variant: call autoRerunWithPatches() explicitly (user button).
   */
  async previewCaseAuto(
    caseId: string,
    opts: { ensureMain?: boolean } = {},
  ): Promise<{ ok: boolean; result?: CaseResult; reason?: string; autoActions?: string[] }> {
    const initial = await this.previewCase(caseId, opts);
    if (!initial.ok || !initial.result) return initial;

    const outcome = initial.result.outcome;
    const eligible = outcome === "FAIL_LOW" || outcome === "INCONCLUSIVE";
    if (!eligible) return initial;

    const autoLog: string[] = [`outcome=${outcome ?? initial.result.status} → auto-review triggered`];

    try {
      // Heuristic-only review (dryRun=true → no AI cost)
      const reviewResult = await this.reviewFailure(caseId, undefined, true, initial.result);
      if (!reviewResult.ok || !reviewResult.review) {
        autoLog.push("heuristic couldn't classify → giving up auto-mode");
        return { ...initial, autoActions: autoLog };
      }
      const review = reviewResult.review;
      autoLog.push(`heuristic: ${review.classification} (${(review.confidence * 100).toFixed(0)}%)`);

      if (review.confidence < 0.85 || !review.suggestedPatch) {
        autoLog.push("confidence < 0.85 or no patch → manual approval needed");
        return { ...initial, autoActions: autoLog };
      }

      // Auto-apply (gated by validator's 3 layers)
      const applied = await this.applyReviewPatch(caseId, undefined, review.suggestedPatch, review);
      if (!applied.ok) {
        autoLog.push(`auto-apply blocked: ${applied.reason}`);
        return { ...initial, autoActions: autoLog };
      }
      autoLog.push(`patch applied: ${review.suggestedPatch.file} (audit: ${applied.auditLogPath?.split("/").pop()})`);

      // One rerun (no further loop here — loop variant is autoRerunWithPatches)
      const rerun = await this.previewCase(caseId);
      if (!rerun.ok || !rerun.result) {
        autoLog.push(`rerun failed: ${rerun.reason}`);
        return { ...rerun, autoActions: autoLog };
      }
      autoLog.push(`rerun outcome: ${rerun.result.outcome ?? rerun.result.status}`);
      return { ok: true, result: rerun.result, autoActions: autoLog };
    } catch (err) {
      autoLog.push(`auto-mode error: ${err instanceof Error ? err.message : String(err)}`);
      return { ...initial, autoActions: autoLog };
    }
  }

  /**
   * Gap C — return historical stats (passRate, flakyScore, recent outcomes)
   * for a case so dashboard can show flakiness indicator. No-op if history
   * log doesn't exist (returns zeroes).
   */
  async caseStats(
    caseId: string,
    slugOverride?: string,
  ): Promise<{ ok: boolean; stats?: import("../step8-run-scenarios/history/index.js").CaseStats; reason?: string }> {
    const slug = slugOverride ?? this.gameSlug;
    if (!slug) return { ok: false, reason: "gameSlug required" };
    const { loadHistory, computeStats } = await import("../step8-run-scenarios/history/index.js");
    const history = await loadHistory(slug, caseId);
    return { ok: true, stats: computeStats(history) };
  }

  /**
   * Phase 7.5 — AI review a failed case. Loads last run result + compiles
   * knowledge → builds Evidence → calls classifier (heuristic-first, AI
   * fallback). Returns the classification + optional suggested patch.
   */
  async reviewFailure(
    caseId: string,
    slugOverride?: string,
    dryRun = false,
    /** Real CaseResult from the most recent run — dashboard passes via
     *  __caseResults[caseId]. When omitted, falls back to synthesized stub
     *  (legacy behavior). */
    realResult?: import("../step8-run-scenarios/case-executor.js").CaseResult,
  ): Promise<{ ok: boolean; review?: import("../step12-failure-review/index.js").ReviewResult; reason?: string }> {
    const slug = slugOverride ?? this.gameSlug;
    if (!slug) return { ok: false, reason: "gameSlug required" };
    const catalog = await loadAiCatalog(slug);
    if (!catalog) return { ok: false, reason: "test-cases.json not found" };
    const tc = catalog.cases.find((c) => c.id === caseId);
    if (!tc) return { ok: false, reason: `case ${caseId} not in catalog` };
    const actionsCache = await loadActionsCache(slug);
    const translated = actionsCache?.cases[caseId];

    const { compileKnowledge } = await import("../knowledge/compiler.js");
    const knowledge = await compileKnowledge(slug);
    if (knowledge.errors.length > 0) {
      return { ok: false, reason: `compiled-knowledge has errors: ${knowledge.errors.join("; ")}` };
    }

    // Use real result from dashboard if provided; else stub (back-compat).
    const caseResult = realResult ?? {
      caseId: tc.id,
      name: tc.name,
      category: tc.category,
      severity: tc.severity as "critical" | "major" | "minor",
      status: "fail" as const,
      actionsExecuted: translated?.actions.length ?? 0,
      assertions: [],
      spin: null,
      durationMs: 0,
      warnings: [],
    };

    const { buildEvidence, classifyFailure } = await import("../step12-failure-review/index.js");
    const evidence = buildEvidence({
      result: caseResult,
      knowledge,
      actionPlan: translated?.actions ?? [],
    });
    const review = await classifyFailure(evidence, { dryRun });
    if (!review) return { ok: false, reason: "heuristic could not classify; AI dryRun blocked" };
    return { ok: true, review };
  }

  /**
   * Phase 7.6 — validate + apply a SuggestedPatch produced by reviewFailure.
   * Writes to registry config file + appends audit log under patches/.
   */
  async applyReviewPatch(
    caseId: string,
    slugOverride: string | undefined,
    patch: import("../step12-failure-review/index.js").SuggestedPatch,
    review: import("../step12-failure-review/index.js").ReviewResult,
  ): Promise<{ ok: boolean; auditLogPath?: string; reason?: string; validation?: import("../step13-patch-apply/index.js").ValidationOutcome }> {
    const slug = slugOverride ?? this.gameSlug;
    if (!slug) return { ok: false, reason: "gameSlug required" };
    const { validatePatch, applyPatch } = await import("../step13-patch-apply/index.js");
    const validation = await validatePatch(slug, patch);
    if (!validation.ok) {
      return { ok: false, reason: `patch failed validation: ${validation.errors.join("; ")}`, validation };
    }
    const applied = await applyPatch({ gameSlug: slug, caseId, review, patch, validation, dryRun: null });
    if (!applied.ok) {
      return { ok: false, reason: `apply failed: ${applied.errors.join("; ")}`, validation };
    }
    // Reload registry so subsequent runs see the patch
    const refreshed = await uiRegistry.load(slug);
    if (refreshed) this.registry = refreshed;
    return { ok: true, auditLogPath: applied.auditLogPath, validation };
  }

  /**
   * Phase 8 item 3 — Auto-rerun loop. Apply patch → rerun case → if still
   * fail → AI re-review → apply next patch → loop max 3 times. Returns
   * RerunResult with status ∈ {"pass", "fail", "escalated"} + log array
   * for dashboard display.
   */
  async autoRerunWithPatches(
    caseId: string,
    slugOverride: string | undefined,
    initialPatch: import("../step12-failure-review/index.js").SuggestedPatch,
    initialReview: import("../step12-failure-review/index.js").ReviewResult,
  ): Promise<import("../step13-patch-apply/types.js").RerunResult> {
    const slug = slugOverride ?? this.gameSlug;
    if (!slug) {
      return { status: "escalated", attemptsUsed: 0, patchesApplied: 0, log: ["gameSlug required"] };
    }
    const { rerunWithPatches } = await import("../step13-patch-apply/rerun-orchestrator.js");
    return rerunWithPatches({
      caseId,
      gameSlug: slug,
      initialPatch,
      initialReview,
      callbacks: {
        applyPatch: async (patch, review) => {
          const r = await this.applyReviewPatch(caseId, slug, patch, review);
          return { ok: r.ok, reason: r.reason };
        },
        rerunCase: async () => {
          const r = await this.previewCase(caseId);
          return {
            ok: r.ok,
            result: r.result ? {
              status: r.result.status,
              outcome: r.result.outcome,
            } : undefined,
            reason: r.reason,
          };
        },
        reReview: async () => {
          const r = await this.reviewFailure(caseId, slug, false);
          return { ok: r.ok, review: r.review, reason: r.reason };
        },
      },
    });
  }

  /**
   * Attach a page-level response listener that watches for `balance=N` in any
   * game-service response (doInit, doSpin, reloadBalance, etc.) and updates
   * `lastBalance`. Called once at session start; persists across reloads
   * because the BrowserContext is shared. Fail-safe: errors swallowed.
   */
  private attachBalanceTracker(): void {
    if (!this.session) return;
    this.session.page.on("response", async (res) => {
      try {
        const url = res.url();
        // PP game service + reload-balance endpoints both carry balance fields.
        if (!/gameService|reloadBalance|gs2c/i.test(url)) return;
        const body = await res.text().catch(() => "");
        if (!body) return;
        // Prefer balance_cash if present (more authoritative on PP) else fall back to balance
        const cashMatch = body.match(/(?:^|&)balance_cash=([\d.]+)/);
        const balMatch = body.match(/(?:^|&)balance=([\d.]+)/);
        const captured = cashMatch ? Number(cashMatch[1]) : balMatch ? Number(balMatch[1]) : null;
        const previous = this.lastBalance;
        if (captured !== null && Number.isFinite(captured)) {
          if (this.lastBalance !== captured) {
            console.log(`[manual/balance] ${this.lastBalance ?? "—"} → ${captured} (from ${new URL(url).pathname})`);
          }
          this.lastBalance = captured;
        }
        // Capture game spec from doInit (or first doSpin) — bet ladder etc.
        if (!this.gameSpec) this.tryCaptureGameSpec(body);

        // Derive game-mechanics on first spin pair (where balance actually
        // dropped). Only run once per game slug — once saved, subsequent
        // sessions load from registry. Detect from request fields + observed
        // balance delta + response win value.
        if (
          this.gameSlug &&
          captured !== null &&
          previous !== null &&
          previous > captured &&    // balance dropped → this was a real bet
          !this.gameMechanicsCached
        ) {
          await this.tryDeriveGameMechanics(res, body, previous, captured);
        }
      } catch {
        // ignore
      }
    });
  }

  /**
   * On observing a real bet deduction, derive { mechanic, betMultiplier }
   * from the request fields + balance delta, save to registry, and inject
   * into the active parser (case-executor reads from registry at start, but
   * we update mid-session for newly-detected games).
   */
  private async tryDeriveGameMechanics(
    res: import("playwright").Response,
    body: string,
    prevBalance: number,
    newBalance: number,
  ): Promise<void> {
    if (!this.gameSlug) return;
    // If registry already has mechanics, mark cached + skip.
    if (this.gameMechanicsCached === undefined) {
      const existing = await gameMechanics.load(this.gameSlug);
      if (existing) {
        this.gameMechanicsCached = existing;
        return;
      }
    }
    if (this.gameMechanicsCached) return;

    const rawReq = res.request().postData();
    if (!rawReq) return;
    const parsedReq = pragmaticProvider.parseBody(rawReq);
    if (!parsedReq) return;
    // Pull win from response body (PP `tw` field). Default to 0 if absent.
    const twMatch = body.match(/(?:^|&)tw=([\d.]+)/);
    const win = twMatch ? Number(twMatch[1]) : 0;
    const derived = deriveGameMechanics({
      parsedRequest: parsedReq,
      balanceBefore: prevBalance,
      balanceAfter: newBalance,
      win,
      rawRequest: rawReq,
    });
    if (!derived) return;
    this.gameMechanicsCached = derived;
    await gameMechanics.save(this.gameSlug, derived);
    console.log(`[manual/game-mechanics] derived for ${this.gameSlug}: mechanic=${derived.mechanic} betMultiplier=${derived.betMultiplier} (l=${derived.waysOrLines}, c=${derived.evidence?.coin}, deducted=${derived.evidence?.deductedFromBalance})`);
  }

  private tryCaptureGameSpec(body: string): void {
    const scMatch = body.match(/(?:^|&)sc=([\d.,]+)/);
    const lMatch = body.match(/(?:^|&)l=(\d+)/);
    const defcMatch = body.match(/(?:^|&)defc=([\d.]+)/);
    const blsMatch = body.match(/(?:^|&)bls=([\d.,]+)/);
    const minMatch = body.match(/(?:^|&)total_bet_min=([\d.]+)/);
    const maxMatch = body.match(/(?:^|&)total_bet_max=([\d.]+)/);
    if (!scMatch || !lMatch) return;
    const coinValues = scMatch[1]!.split(",").map(Number).filter((n) => Number.isFinite(n) && n > 0);
    const lines = Number(lMatch[1]);
    const defaultCoin = defcMatch ? Number(defcMatch[1]) : coinValues[0]!;
    const betLevels = blsMatch ? blsMatch[1]!.split(",").map(Number).filter(Number.isFinite) : [];
    const betMin = minMatch ? Number(minMatch[1]) : coinValues[0]! * lines;
    const betMax = maxMatch ? Number(maxMatch[1]) : coinValues[coinValues.length - 1]! * lines;
    this.gameSpec = {
      coinValues,
      lines,
      defaultCoin,
      betLevels,
      betMin,
      betMax,
      defaultBet: defaultCoin * lines,
      betLadder: coinValues.map((c) => c * lines),
    };
    console.log(`[manual/spec] captured: ladder=${this.gameSpec.betLadder.slice(0, 5).join(",")}…(${this.gameSpec.betLadder.length}) default=${this.gameSpec.defaultBet} min=${betMin} max=${betMax}`);
  }

  /**
   * Hybrid wait between batch cases. Combines:
   *   1. Fixed minimum delay (animation start has time to begin)
   *   2. Pixel-diff loop: crop around spinButton baseline vs live every 500ms.
   *      When N consecutive samples match baseline (within threshold) → settled.
   *   3. Hard cap (default 45s) for safety (free spins / cascade chain).
   *
   * Returns settled=true when stable confirmed, false if cap reached.
   */
  async waitForStable(opts: {
    uiKey?: string;
    minDelayMs?: number;
    maxMs?: number;
    pollMs?: number;
    stableSamples?: number;
    diffThreshold?: number;
  } = {}): Promise<{ ok: boolean; settled: boolean; durationMs: number; samples: number; reason?: string }> {
    if (!this.session || !this.gameSlug || !this.registry) return { ok: false, settled: false, durationMs: 0, samples: 0, reason: "no active session" };
    const uiKey = opts.uiKey ?? "spinButton";
    const el = this.registry[uiKey];
    if (!el?.baselineScreenshot) {
      // No baseline to diff against → fall back to fixed wait
      const fallback = opts.minDelayMs ?? 3000;
      await this.session.page.waitForTimeout(fallback);
      return { ok: true, settled: true, durationMs: fallback, samples: 0, reason: "no baseline; used fixed delay" };
    }
    const baselinePath = path.join(dirForGame(this.gameSlug), "baselines", el.baselineScreenshot);
    let baseline: Buffer;
    try {
      baseline = await readFile(baselinePath);
    } catch {
      const fallback = opts.minDelayMs ?? 3000;
      await this.session.page.waitForTimeout(fallback);
      return { ok: true, settled: true, durationMs: fallback, samples: 0, reason: "baseline unreadable; used fixed delay" };
    }

    const minDelay = opts.minDelayMs ?? 1500;
    const maxMs = opts.maxMs ?? 45_000;
    const pollMs = opts.pollMs ?? 500;
    const stableSamples = opts.stableSamples ?? 2;
    const diffThreshold = opts.diffThreshold ?? 0.05;

    const start = Date.now();
    await this.session.page.waitForTimeout(minDelay);

    const region = regionAround(el.x, el.y, 80, 80);
    let consecutiveStable = 0;
    let samples = 0;
    while (Date.now() - start < maxMs) {
      try {
        const { ratio, changed } = await diffVsBaseline(this.session.page, baseline, region, {
          pixelThreshold: 0.1,
          changeThreshold: diffThreshold,
        });
        samples++;
        if (!changed) consecutiveStable++;
        else consecutiveStable = 0;
        if (consecutiveStable >= stableSamples) {
          return { ok: true, settled: true, durationMs: Date.now() - start, samples };
        }
        void ratio;
      } catch {
        // Diff failure (size mismatch, etc.) — keep polling
      }
      await this.session.page.waitForTimeout(pollMs);
    }
    return { ok: true, settled: false, durationMs: Date.now() - start, samples, reason: `timed out after ${maxMs}ms` };
  }

  async stop(): Promise<void> {
    if (this.session) {
      await closeBrowser(this.session);
    }
    this.session = null;
    this.gameSlug = null;
    this.gameUrl = null;
    this.startedAt = null;
    this.registry = null;
    this.verifyState = {};
    this.lastBalance = null;
  }
}

export const manualSession = new ManualSessionManager();

export type RegisteredGame = {
  gameSlug: string;
  gameUrl: string;
  /** Friendly game name from provider-cache (e.g. "Mahjong Wins 2"). Matches
   *  the name shown in RUN SUMMARY. Undefined when provider-cache missing. */
  gameName?: string;
  /** Provider label from provider-cache (e.g. "Pragmatic" / "Generic"). */
  provider?: string;
  createdAt: string;
  lastValidatedAt?: string;
  elementCount: number;
  verifiedCount: number;
  pendingCount: number;
  rejectedCount: number;
};

/**
 * Update gameUrl in _meta.json without touching the registry. Use case: token
 * in URL expired → change token, registry (UI coords + sub-states) still valid.
 * If session is currently active on this slug, also navigates the browser to
 * the new URL.
 */
export async function updateGameUrl(gameSlug: string, newUrl: string): Promise<{ ok: boolean; reason?: string }> {
  try {
    new URL(newUrl);
  } catch {
    return { ok: false, reason: "invalid URL" };
  }
  const m = await meta.load(gameSlug);
  if (!m) return { ok: false, reason: `No registry for ${gameSlug}` };
  await meta.save(gameSlug, { ...m, gameUrl: newUrl });

  // If active session targets this slug, navigate page to new URL so QA can
  // verify the existing registry still maps correctly under the new token.
  if (manualSession.status().active && manualSession.status().gameSlug === gameSlug) {
    await manualSession.navigateTo(newUrl);
  }
  return { ok: true };
}

/**
 * Delete a game and ALL related fixtures: registry folder, pre-game record,
 * provider spec, recorded scenarios, and statistical debug dumps. Stops the
 * active session first if it targets this slug. Irreversible.
 */
export async function deleteGame(gameSlug: string): Promise<{ ok: boolean; removed: string[]; reason?: string }> {
  // Path-traversal guard — slug must be a plain folder name.
  if (!/^[a-zA-Z0-9_-]+$/.test(gameSlug)) {
    return { ok: false, removed: [], reason: `invalid slug "${gameSlug}"` };
  }
  // If the active session is on this game, stop it first so the browser +
  // file handles are released before we delete.
  if (manualSession.status().active && manualSession.status().gameSlug === gameSlug) {
    await manualSession.stop().catch(() => {});
  }

  const removed: string[] = [];
  const rmPath = async (p: string) => {
    try {
      await rm(p, { recursive: true, force: true });
      removed.push(p);
    } catch {
      // ignore — path may not exist
    }
  };

  // 1. Main registry folder (registry + case-evidence + history + debug-*).
  await rmPath(dirForGame(gameSlug));
  // 2. Single-file per-slug fixtures.
  await rmPath(path.join("fixtures", "pre-game", `${gameSlug}.json`));
  // 3. Per-slug folders elsewhere.
  await rmPath(path.join("fixtures", "specs", gameSlug));
  await rmPath(path.join("fixtures", "scenarios", gameSlug));
  // 4. Timestamped statistical debug dumps: `<slug>-<ISO>-debug`.
  try {
    const statDir = path.join("fixtures", "statistical");
    const entries = await readdir(statDir);
    for (const e of entries) {
      if (e === gameSlug || e.startsWith(`${gameSlug}-`)) {
        await rmPath(path.join(statDir, e));
      }
    }
  } catch {
    // statistical dir may not exist
  }

  if (removed.length === 0) {
    return { ok: false, removed, reason: `nothing found for "${gameSlug}"` };
  }
  return { ok: true, removed };
}

/**
 * List all games that have a registry on disk. Used by dashboard to show
 * "previously registered" games so QA can resume without re-discovery.
 */
export async function listRegisteredGames(): Promise<RegisteredGame[]> {
  const registryRoot = "fixtures/registry";
  let dirs: string[] = [];
  try {
    dirs = await readdir(registryRoot);
  } catch {
    return [];
  }
  const out: RegisteredGame[] = [];
  for (const slug of dirs) {
    try {
      const m = await meta.load(slug);
      const reg = await uiRegistry.load(slug);
      if (!m || !reg) continue;
      let verified = 0, pending = 0, rejected = 0;
      for (const el of Object.values(reg)) {
        if (!el) continue;
        const s = el.status ?? "pending";
        if (s === "verified") verified++;
        else if (s === "rejected") rejected++;
        else pending++;
      }
      // Friendly name + provider from provider-cache (same source as RUN
      // SUMMARY). Missing cache → leave undefined; dashboard falls back to slug.
      const pc = await providerCache.load(slug).catch(() => null);
      out.push({
        gameSlug: slug,
        gameUrl: m.gameUrl,
        gameName: pc?.gameName,
        provider: pc?.provider,
        createdAt: m.createdAt,
        lastValidatedAt: m.lastValidatedAt,
        elementCount: Object.keys(reg).length,
        verifiedCount: verified,
        pendingCount: pending,
        rejectedCount: rejected,
      });
    } catch {
      // skip games with corrupt registry
    }
  }
  // Most recent first
  out.sort((a, b) => (b.lastValidatedAt ?? b.createdAt).localeCompare(a.lastValidatedAt ?? a.createdAt));
  return out;
}
